name: Flutter Windows Release

on:
  push:
    branches:
      - dev

jobs:
  build_windows:
    name: Build Windows Release
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.1

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Create .env file
        shell: bash
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ailixir-windows-release
          path: build/windows/x64/runner/Release/
